[package]
name = "docgpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
lopdf = "0.30.0"
serde = { version = "1.0", features = ["derive"] }
