    name: Build For All Targets
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              target: x86_64-unknown-linux-gnu
              default: true
        - name: Build
          uses: actions-rs/cargo@v1
          with:
              command: build
              args: --release --all-targets
